FROM cypress/included:latest

RUN apt update && apt upgrade -y && \
apt clean && \
rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm && \
pnpm --version


# RUN touch /root/.cache && chmod -R 777 /root/.cache

ENV SHELL=/bin/bash

# RUN mkdir -p /home/node/.ssh && \
# ssh-keyscan github.com >> /home/node/.ssh/known_hosts

RUN pnpm setup

# ENV PNPM_HOME="/home/node/.local/share/pnpm"
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"

RUN pnpm config set store-dir "${PNPM_HOME}/store" && \
pnpm install -g typescript && \
pnpm -g install pnpm && \
pnpm --version && tsc --version

ENTRYPOINT [ "" ]

# USER node
