name: Poc Cypress Dev Container 


services:
  # App Under test. For this example we use the kitchensink example from cypress.
  # https://github.com/cypress-io/cypress-example-kitchensink
  cypress-kitchensink:
    # Base image wiht node and pnpm. Ref. https://github.com/marcandreuf/base-images
    image: ghcr.io/marcandreuf/base-images/frontend-node22-pnpm:main
    volumes:
      - ${HOME}/.local/share/pnpm:/home/root/.local/share/pnpm
      - ../:/home/node/workspace
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 3


  # Cypress Open with display setup
  # cypress-dev-env:
  #   image: "cypress/included:latest"
  #   container_name: cypress-open-container
  #   depends_on:
  #     - cypress-kitchensink
  #   environment:
  #     - DISPLAY
  #     - CYPRESS_baseUrl=http://localhost:8080
  #   working_dir: /e2e
  #   network_mode: host
  #   entrypoint: ""
  #   volumes:
  #     - ../cypress-example-kitchensink:/e2e
  #     - ~/.Xauthority:/root/.Xauthority:ro
  #   #command: "open --detached --project . --config video=false"
  #   command: /bin/sh -c "while sleep 1000; do :; done"
