# Start from the official cypress docker image.
FROM cypress/included:latest

RUN apt update && apt upgrade -y && \
apt clean && \
rm -rf /var/lib/apt/lists/*

# Install pnpm
RUN npm install -g pnpm && \
pnpm --version

# Set bash as the default shell
ENV SHELL=/bin/bash

# Init pnpm setup
RUN pnpm setup

# Set the pnpm store directory that will be synched with the host machine on the docker compose file.
# Install typescript and force update pnpm
ENV PNPM_HOME="/home/node/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"
RUN pnpm config set store-dir "${PNPM_HOME}/store" && \
pnpm install -g typescript && \
pnpm self-update && \
pnpm --version && tsc --version

# Deactivate cypress included entrypoint
ENTRYPOINT [ "" ]

# Start the container with the command node as the default command to keep the container opened as a dev container.
CMD [ "node" ]

USER node
